### ISSUE TITLE
Doesn't work with FeatureCollections: java.lang.IllegalStateException: Expected a name but was STRING at line 1 column 12 path $.type

### ISSUE THREAD

**Issue by laoyang** [filosganga/geogson#41]
Crashes with the sample json from: [https://en.wikipedia.org/wiki/GeoJSON](url):
`
{ "type": "FeatureCollection",
    "features": [
      { "type": "Feature",
        "geometry": {"type": "Point", "coordinates": [102.0, 0.5]},
        "properties": {"prop0": "value0"}
        },
      { "type": "Feature",
        "geometry": {
          "type": "LineString",
          "coordinates": [
            [102.0, 0.0], [103.0, 1.0], [104.0, 0.0], [105.0, 1.0]
            ]
          },
        "properties": {
          "prop0": "value0",
          "prop1": 0.0
          }
        },
      { "type": "Feature",
         "geometry": {
           "type": "Polygon",
           "coordinates": [
             [ [100.0, 0.0], [101.0, 0.0], [101.0, 1.0],
               [100.0, 1.0], [100.0, 0.0] ]
             ]
         },
         "properties": {
           "prop0": "value0",
           "prop1": {"this": "that"}
           }
         }
       ]
     }
`
Stack trace:

03-31 04:22:21.327 29843-29843/com..myapplication E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       Process: com..myapplication, PID: 29843
                                                                       java.lang.RuntimeException: Unable to start activity ComponentInfo{com..myapplication/com..myapplication.MainActivity}: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a name but was STRING at line 1 column 12 path $.type
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                           at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                           at android.os.Looper.loop(Looper.java:148)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                        Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a name but was STRING at line 1 column 12 path $.type
                                                                           at com.google.gson.Gson.fromJson(Gson.java:891)
                                                                           at com.google.gson.Gson.fromJson(Gson.java:844)
                                                                           at com.google.gson.Gson.fromJson(Gson.java:793)
                                                                           at com.google.gson.Gson.fromJson(Gson.java:765)
                                                                           at com..myapplication.MainActivity.onCreate(MainActivity.java:95)
                                                                           at android.app.Activity.performCreate(Activity.java:6237)
                                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                           at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                           at android.os.Looper.loop(Looper.java:148) 
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                        Caused by: java.lang.IllegalStateException: Expected a name but was STRING at line 1 column 12 path $.type
                                                                           at com.google.gson.stream.JsonReader.nextName(JsonReader.java:794)
                                                                           at com.github.filosganga.geogson.gson.FeatureCollectionAdapter.read(FeatureCollectionAdapter.java:54)
                                                                           at com.github.filosganga.geogson.gson.FeatureCollectionAdapter.read(FeatureCollectionAdapter.java:19)
                                                                           at com.google.gson.Gson.fromJson(Gson.java:879)
                                                                           at com.google.gson.Gson.fromJson(Gson.java:844) 
                                                                           at com.google.gson.Gson.fromJson(Gson.java:793) 
                                                                           at com.google.gson.Gson.fromJson(Gson.java:765) 
                                                                           at com..myapplication.MainActivity.onCreate(MainActivity.java:95) 
                                                                           at android.app.Activity.performCreate(Activity.java:6237) 
                                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107) 
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369) 
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                           at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                           at android.os.Looper.loop(Looper.java:148) 
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by filosganga** [comment]
Thanks to report, I will take a look at it now.

**Comment by filosganga** [comment]
Hi @laoyang the version 1.1.96, that solves your issue, has been released.

**Comment by laoyang** [comment]
Thanks! It's great that you actively work on it. Keep up the good work
